function ex2()
clearvars; close all; clc;
S = load('audioNew.mat');
x_new = S.x_new; Fs = S.Fs;
disp('Playing cleaned signal x_new...');
player = audioplayer(x_new, Fs);
playblocking(player);
N = numel(x_new);
f_ax = (0:N-1)*(Fs/N);
Xn = fft(x_new);
figure('Name','Cleaned Spectrum','Color','w');
semilogy(f_ax(1:floor(N/2)), abs(Xn(1:floor(N/2))), 'LineWidth',1.4);
grid on; box on;
xlabel('Frequency (Hz)'); ylabel('Magnitude');
title('FFT of x_new');
factor = 25;
x_samp = x_new(1:factor:end);
Fs_new = Fs/factor;
disp('Playing naive downsampled signal...');
player = audioplayer(x_samp, Fs_new);
playblocking(player);
Nf = 101; n = 0:Nf-1; M = (Nf-1)/2;
fc = Fs_new/2;
x_rel = n - M;
h_ideal = sin(2*pi*fc/Fs .* x_rel) ./ (pi * x_rel);
h_ideal(M+1) = 2*fc/Fs;
w = 0.54 - 0.46*cos(2*pi*n/(Nf-1));
h_lp = (h_ideal .* w);
h_lp = h_lp / sum(h_lp);
x_low = conv(x_new, h_lp, 'same');
x_samp2 = x_low(1:factor:end);
disp('Playing anti-aliased downsampled signal...');
player = audioplayer(x_samp2, Fs_new);
playblocking(player);
N2 = numel(x_samp);
f2 = (0:N2-1)*(Fs_new/N2);
Xna = fft(x_samp); Xan = fft(x_samp2);
figure('Name','Sampling Comparison','Color','w');
semilogy(f2(1:floor(N2/2)), abs(Xna(1:floor(N2/2))), '--','LineWidth',1.2); hold on;
semilogy(f2(1:floor(N2/2)), abs(Xan(1:floor(N2/2))), '-','LineWidth',1.2); hold off;
grid on; box on;
xlabel('Frequency (Hz)'); ylabel('Magnitude');
title('Naive vs Anti-aliased Downsampling');
legend('Naive','Anti-aliased','Location','northeast','Box','off');
xticks([0,100,500,1000,2000,4000]);
ylim([1e0,1e6]);
save('result_ex2.mat','x_samp','x_samp2','Fs_new');
end
% Plot 1: Filtered Spectrum
figure;
semilogy(f(1:N/2), abs(X(1:N/2)), '--'); hold on;
semilogy(f(1:N/2), abs(Xc(1:N/2)));
legend('Original', 'Filtered');
xlabel('Frequency (Hz)'); ylabel('Magnitude'); grid on;
title('Original vs Filtered Spectrum');
saveas(gcf, 'filtered_spectrum.png');
% Plot 2: Cleaned Spectrum
figure;
semilogy(f(1:N/2), abs(Xn(1:N/2)));
xlabel('Frequency (Hz)'); ylabel('Magnitude');
title('FFT of Cleaned Signal'); grid on;
saveas(gcf, 'cleaned_spectrum.png');
% Plot 3: Downsampling Comparison
figure;
semilogy(f2(1:N/2), abs(Xna(1:N/2)), '--'); hold on;
semilogy(f2(1:N/2), abs(Xan(1:N/2)));
legend('Naive', 'Anti-aliased');
xlabel('Frequency (Hz)'); ylabel('Magnitude');
title('Naive vs Anti-aliased Downsampling'); grid on;
saveas(gcf, 'downsampling_comparison.png');
